wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
    session_history: code/_session_history.ipynb
    start_time: 1629869565
    t:
      1:
      - 1
      - 5
      - 6
      - 7
      - 8
      2:
      - 1
      - 5
      - 6
      - 7
      - 8
      3:
      - 2
      4: 3.7.7
      5: 0.12.0
      8:
      - 1
      - 5
